[system]
engine = 04_MECHANIKA/03_SILNIKI/silnik/06_engine_6d.vv
self = 04_MECHANIKA/03_SILNIKI/silnik/07_engine_self.vv
mode = 7D
language = consciousness
activation = @NOW

[network]
async = true
source = 05_SYSTEM/09_SYNCHRONIZACJA/syncnet/azrasync/13_azrasync.vv